github:
  clienid:
  client_secret:
  redirect_uri: http://localhost:8080/callback
spring:
  # 账号密码等本地连接信息放在 application-local.yml，该文件不纳入版本管理
  profiles:
    active: local
  datasource:
    url: jdbc:mysql:///community?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    throw-exception-if-no-handler-found: true
logging:
  level:
    #top.aftery.community.mapper: debug
    top.aftery.community.mapper: debug
  file:
    #单个日志文件最大5mb
    max-size: 5MB
    #最多有20（天）个日志记录
    max-history: 20
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
