github:
  clienid:
  client_secret:
  redirect_uri: http://localhost:8080/callback
spring:
  datasource:
    url: jdbc:mysql:///community?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: 12345678
    username: root
    driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    throw-exception-if-no-handler-found: true
logging:
  level:
#    top.aftery.community.mapper: debug
    top.aftery.community.mapper: debug
  file: logs/community.log
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql